name: find-replace-in-files
description: find and replace strings in files

inputs:
  bpwd:
    required: true
    description: base working directory to start from
    default: "${{ github.workspace }}"
  files:
    required: true
    description: 'pattern to match files to search'
    default: '*.ps1'
  vars:
    required: true
    description: 'JSON array containing var names and secrets'

runs:
  using: "composite"
  steps:
    -
      run: |
        bpwd=${{ inputs.bpwd }}
        echo "bpwd: $bpwd"
        json='${{ inputs.vars }}'
        echo "json: $json"
        echo "files: ${{ inputs.files }}"
        length=$(echo $json | jq 'length')
        for i in $(find $bpwd -name "${{ inputs.files }}")
        do
          for ((j=0;j<$length;j++))
          do
            name=$(jq -r ".vars[$j].name" $json)
            secret=$(jq -r ".vars[$j].secret" $json)
            sed -i "s/$name/$secret/g" $i
          done
        done
      shell: bash